#%RAML 0.8
title: Test Service - greetings!
version: v1.0
mediaType:  application/json
baseUri: http://www.api.com

/greet:
  get:
    queryParameters:
      who:
        description: Who to greet
        example: "John Doe"

    responses:
      200:
        description: Testing the service
        body:
          application/json:
            example: !include greet.sample

/kill:
  get:
    queryParameters:
      who:
        description: Who to kill
        example: "John Doe"

    responses:
      200:
        description: Testing the service
        body:
          application/json:
            example: !include kill.sample

/needParameter:
  get:
    queryParameters:
      fill:
        description: Needed parameter
        example: 'fill-me'
        required: true
    responses:
      200:
        description: I was filled

